language: node_js
node_js:
  - "8"
  - "10"
  - "12"

install: 
  - npm install

script: 
  - npm test
  - npm run build

deploy:
  skip_cleanup: true
  on:
    repo: swimmadude66/jsonnet-cli
    node: "10"
    tags: true
    branch: master
  provider: npm
  email: "swimmadude66@gmail.com"
  api_key: 
    secure: "T4RZZe5JlNUBf5i+L8lC1gRFxzIj8/ZfhI21kzHiDbQ3BN5dEcmbD812O8IK6xx22/tRMWrOKlhN+MJRJi8z2Q9J6PC/R6PhrE+FJz8bUn5MVmuvXYYbuNkvXinCURm5jLaLSVZ5rxVIyYA26fJMfgNYjNFwAKcwHYgytkBd/1ItmLwnfM1M0gm9tfzRy9Q/7wb9TyyOd4mfozRuppC1MTqeHjaEATMZ8G/RhXGKpaRPOALOTfsPAJxAFsA1B6DYE4K5V5VbVMk1jmQ6H77HZFUVzb4BNMMA/kByD27pkGE21WmCReBFYj9cyUURial214mt4gdQXioVWxaU0OHpkb2KQbZzQoInZ0yY0PbxbtmnqLaXC1fVY+2subMmEHMmeJ/M9rmrlHShrdb8UFOhzvNOoo8TaR0TxznjQKvqoTJcYbTZZGl9DiBXqzwL2Khkrhh3WsgIKEpGzJsdsNO06L/f5h4XiScM4M3XY4HJNLlu84xmSgMzbHr8zz6d4W6Lqk4Cua+RLc5HQzxmyx86AWwsQl8GBkzsMdTqRbxhXBCDQ5az8tYe+Vbp1BU6Kl9dtqpKS+AuQCuywQfJUYZCyGvez/oUGXbCS/OKmgVW4jJNIOPOMMyhIHHbHEbNwWH7tw518pREUZ/7vvhEY1Rog3j/ktGBeMWux9kZ/tcXu0s="